import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { HeaderProvider } from "@/components/Header/header";
import ReduxProvider from "@/providers/ReduxProvider";
import MiniPlayer from "@/components/jam/MiniPlayer";
import AuthSyncProvider from "@/providers/AuthSyncProvider";
import LoginModal from "@/components/auth/LoginModal";
import AppViewManager from "@/components/AppViewManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mushflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ReduxProvider>
            <AuthSyncProvider>
              <HeaderProvider>
                <AppViewManager>
                  {children}
                </AppViewManager>
                <MiniPlayer />
                <LoginModal />
              </HeaderProvider>
            </AuthSyncProvider>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
