"use client";

import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import dynamic from 'next/dynamic';

// Dynamically import components that might use window
const ClientSideProviders = dynamic(() => import('@/components/ClientSideProviders'), { ssr: false });

// Add type declaration for the global AgoraRTM object
declare global {
  interface Window {
    AgoraRTM?: any;
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Mushflow</title>
        <meta name="description" content="Generated by create next app" />
        {/* Load Agora RTM SDK from CDN as a fallback */}
        <Script 
          src="https://download.agora.io/sdk/release/agora-rtm-2.2.1.js" 
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSideProviders>
          {children}
        </ClientSideProviders>
      </body>
    </html>
  );
} 